# Data Science Lab: Lab 6

Submit:

A pdf of your notebook with solutions.
A link to your colab notebook or also upload your .ipynb if not working on colab.

# Goals of this Lab

**Fully Connected Models and XOR**


1. How to create data objects that pytorch can use
2. How to create a dataloader
3. How to define a basic fully connected single layer model
4. How to define a multi-layer fully connected model
5. How to add non-linear activation functions.
6. How to add layers in two different ways

We also see the importance of nonlinear activation functions directly, by experimenting with the simple 4-data-point XOR example that we saw in class.

We also see that neural networks are fundamentally different than, say, logistic regression or linear regression, in that they can get stuck in local minima. A simple way to say this is that a different random seed may lead to a different solution.

We explore how capacity (the size of the neural network) could affect this situation.

**Note:** Make sure that you fix a random seed so that you can replicate your solutions. This is always a good practice, and in particular important here, as we see below.

In [2]:
import torch
import numpy as np
import time
from tqdm.notebook import tqdm

# First we define a linear regressor.
This is the same as a fully connected layer. It will be a building block in making deeper neural networks with fully connected layers.

In [3]:
# We define our first class: LinearRegressor
#
class LinearRegressor(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define the layer(s) needed for the linear model.
        """
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim, bias = True) # just linear

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.linear(x)
        return torch.flatten(x)


    # defining a separate predict function is useful for multi-class
    # classification as we will see later. Here it is
    # unnecessary.

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.linear(x)
        return torch.flatten(x)




## Problem 1:

Now you will use torch.nn.Sequential (see https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html) to construct a two layer neural network, with two fully connected layers (no non-linearity yet). Thus, you will combine torch.nn.Sequential with torch.nn.Linear that you saw above.


Design your network so that the first layer has as many neurons as the input.

Note: you have only one line to fill in here.

In [4]:
class TwoLayerLinearRegressor(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define a model that stacks two linear fully connected layers.
        """
        super().__init__()
        self.TLL = torch.nn.Sequential(
            torch.nn.Linear(input_dim, input_dim),
            torch.nn.Linear(input_dim, output_dim)
        )# TO DO: complete this equality, using torch.nn.Sequential

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.TLL(x)
        return torch.flatten(x)

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.TLL(x)
        return torch.flatten(x)






## Problem 2

Now you will create the same network, but using different syntax: you will not use torch.nn.Sequential. You need to fill in the two lines as noted by the comments.

In [5]:
class TwoLayerLinearRegressor2(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define a model that stacks two linear fully connected layers.
        """
        super().__init__()
        self.fc1 = torch.nn.Linear(input_dim, input_dim) # TO DO
        self.fc2 = torch.nn.Linear(input_dim, output_dim) # TO DO

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """

        x = self.fc1(x)
        x = self.fc2(x)
        return torch.flatten(x)

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.fc1(x)
        x = self.fc2(x)
        return torch.flatten(x)


## Problem 3

Now you will define a 2 layer neural network with ReLU activation at the first layer. In other words:

Let $x$ be the input.
Then writing $z = Wx + c$, $h=$ReLU$(z)$ is the first layer's neurons. Then the output is $y = w\cdot z+d$.

Create this neural network using the torch.nn.Sequential command. Conceptually, it may help to realize that this neural network is: a fully connected layer followed by a ReLU, followed by a fully connected layer.

Also see: https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html

Note: You have only one line to fill in here.

In [6]:
class TwoLayerNonLinearRegressor(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define a model that has a linear layer, a ReLU layer and another linear layer.
        """
        super().__init__()
        self.linear = torch.nn.Sequential(
            torch.nn.Linear(input_dim, input_dim),
            torch.nn.ReLU(),
            torch.nn.Linear(input_dim, output_dim)
        )# TO DO

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.linear(x)
        return torch.flatten(x)

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.linear(x)
        return torch.flatten(x)



## Problem 4

Do this one more time, but now without torch.nn.Sequential.

You have three lines to fill in here.

In [7]:
# We now do this again, without using nn.sequential
# in order to illustrate different syntax.

class TwoLayerNonLinearRegressor2(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define a model that has a linear layer, a ReLU layer and another linear layer.
        """
        super().__init__()
        self.fc1 = torch.nn.Linear(input_dim, input_dim) # TO DO
        self.relu = torch.nn.ReLU() # TO DO
        self.fc2 = torch.nn.Linear(input_dim, output_dim) # TO DO

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """

        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return torch.flatten(x)

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return torch.flatten(x)

## Problem 5 (Nothing to turn in)

Read the documentation https://pytorch.org/docs/stable/optim.html to see what are the options pytorch provides for an optimizer, and what the parameters are.

## Problem 6

Explain what the code


```
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
```
and


```
model.to(device)
x = x.to(device)
y = y.to(device)
```

does. This does not have to be a completely rigorous definition -- just explain enough to make clear that you understand what the code is doing and why it's important.



The first line checks if there is a CUDA-enabled GPU on the device and will run subsequent models using that if there is, otherwise it will just use the CPU. GPU's often speed up training with parallelism so it's beneficial to use it if available. The following lines moves the model's parameters to the specified device as well as the input data X and labels y.

## Problem 7

Modify the code below for the training loop, so that in addition to training, you output a curve of the training error over each epoch.

In [8]:
# Now we define a function for training
# Note each of the arguments that it takes
import matplotlib.pyplot as plt

#TODO: add a plot of the training error over each epoch

def train(model, data_train, data_val, device, lr=0.01, epochs=5000):
    """
    Train the model.

    Input:
      model (torch.nn.Module): the model to train
      data_train (torch.utils.data.Dataloader): yields batches of data
      data_val (torch.utils.data.Dataloader): use this to validate your model
      device (torch.device): which device to use to perform computation

      (optional) lr: learning rate hyperparameter
      (optional) epochs: number of passes over dataloader
    """

    # Setup the loss function to use: mean squared error
    loss_function = torch.nn.MSELoss(reduction = 'sum')

    # Setup the optimizer -- just generic ADAM
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    train_losses = []

    # Wrap in a progress bar.
    for epoch in tqdm(range(epochs)):
        # Set the model to training mode.
        model.train()
        train_loss = 0

        for x, y in data_train:
            x = x.to(device)
            y = y.to(device)

            # Forward pass through the network
            output = model(x)

            # Compute loss
            loss = loss_function(output, y)
            # losses.append(loss)
            # update model weights.
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        train_loss /= len(data_train)
        train_losses.append(train_loss)

        # Set the model to eval mode and compute accuracy.
        model.eval()

        accuracys_val = list()

        for x, y in data_val:
            x = x.to(device)
            y = y.to(device)

            y_pred = model.predict(x)

    
    # Plotting the array vs its index
    # plt.plot(train_losses)  # Plot the array
    # plt.xlabel('# of Epochs')
    # plt.ylabel('Training Error')
    # plt.title('Training Error vs. Num Epochs')
    #     # plt.grid(True)  # Optional: adds gridlines for better readability
    # plt.show()

    

In [9]:
# We write a function that takes a model, evaluate on the validation
# data set and returns the predictions

def evaluate_model(model,data_val,device):
  model.eval()
  output_vals = list()
  accuracys_val = list()
  for x, y in data_val:
            x = x.to(device)
            y = y.to(device)

            y_pred = model.predict(x)
            output_vals.append(y_pred)
            # accuracy_val = (y_pred == y).float().mean().item()
            # accuracys_val.append(accuracy_val)

  # accuracy = torch.FloatTensor(accuracys_val).mean().item()
  return output_vals

## Problem 8 (Nothing to turn in)

Read the documentation and try to understand what a dataloader is. You can start here https://pytorch.org/docs/stable/data.html but there are many tutorials out there as well.

In [10]:
# Creating the data: Linear Regression on Linear Data
from torch.utils.data import TensorDataset, DataLoader
N = 15
X = np.random.randn(N,3)
beta = np.array([1,-1,2])
Y = np.dot(X,beta)
tensor_x = torch.Tensor(X) # transform to torch tensor
tensor_y = torch.Tensor(Y)
print('These are the labels:\n',Y)
print('These are the features:\n',X)

m = 1 # Batch size
data = TensorDataset(tensor_x,tensor_y) # create your datset
data_train = DataLoader(data,batch_size = m, shuffle = True) # create your dataloader with training data
data_val = DataLoader(data) # create your dataloader with validation data, here same as training

These are the labels:
 [-2.92164093 -2.35851639 -0.79013586 -2.96089867  1.38743002 -1.88085613
  2.77268172  1.98250132 -1.78695002 -0.03357685  1.65721457  1.34342075
 -0.83757275 -1.18249513 -3.6752463 ]
These are the features:
 [[-0.82192981  0.45696099 -0.82137506]
 [-0.34173895 -0.08370911 -1.05024328]
 [-0.45853501 -0.24157728 -0.28658906]
 [-1.49122919  0.63967039 -0.41499954]
 [ 0.53036929  0.25490201  0.55598137]
 [-0.51036883  0.50289277 -0.43379726]
 [ 2.14827106 -1.48717742 -0.43138338]
 [-0.64680928 -0.4359085   1.09670105]
 [-1.22189536  0.93224377  0.18359456]
 [ 1.00232561 -1.11559384 -1.07574815]
 [-0.0885562  -1.05422868  0.34577104]
 [ 0.09810545  1.80515341  1.52523435]
 [ 0.46070493  0.37850814 -0.45988477]
 [ 0.77437559 -0.02828518 -0.99257795]
 [-0.62222489  0.28536014 -1.38383063]]


## Now we train and evaluate the linear model.

In [11]:
# Define the model we wish to use, and train it.
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = LinearRegressor(3, 1)
model.to(device)

train(model, data_train, data_val, device)

  0%|          | 0/5000 [00:00<?, ?it/s]

## Here is some code for getting the parameters of the model.

In [12]:
# Now let's get the model parameters.
# We can see that we have succeeded in learning beta: [1,-1,2]
for name, param in model.named_parameters():
  print (name, param.data)

# If we wanted to, we could also only print the ones that we update (may be useful for more complex models)
"""
for name, param in model.named_parameters():
    if param.requires_grad:
        print (name, param.data)
"""

linear.weight tensor([[ 1.0000, -1.0000,  2.0000]])
linear.bias tensor([-4.7753e-07])


'\nfor name, param in model.named_parameters():\n    if param.requires_grad:\n        print (name, param.data)\n'

In [13]:
# Now let's move to our second model: the two layer linear regressor.
# We again define the model using the class we created.
# Then we train the model, as above.

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model2 = TwoLayerLinearRegressor(3, 1)
model2.to(device)

train(model2, data_train, data_val, device)

  0%|          | 0/5000 [00:00<?, ?it/s]

In [14]:
# Let's see how well this model agrees with the training data
output_values = evaluate_model(model2,data_val,device)
print('Ground Truth:\n',Y)
print('Model Output:\n',output_values)

Ground Truth:
 [-2.92164093 -2.35851639 -0.79013586 -2.96089867  1.38743002 -1.88085613
  2.77268172  1.98250132 -1.78695002 -0.03357685  1.65721457  1.34342075
 -0.83757275 -1.18249513 -3.6752463 ]
Model Output:
 [tensor([-2.9228], grad_fn=<ViewBackward0>), tensor([-2.3594], grad_fn=<ViewBackward0>), tensor([-0.7905], grad_fn=<ViewBackward0>), tensor([-2.9621], grad_fn=<ViewBackward0>), tensor([1.3875], grad_fn=<ViewBackward0>), tensor([-1.8818], grad_fn=<ViewBackward0>), tensor([2.7735], grad_fn=<ViewBackward0>), tensor([1.9831], grad_fn=<ViewBackward0>), tensor([-1.7879], grad_fn=<ViewBackward0>), tensor([-0.0336], grad_fn=<ViewBackward0>), tensor([1.6579], grad_fn=<ViewBackward0>), tensor([1.3429], grad_fn=<ViewBackward0>), tensor([-0.8383], grad_fn=<ViewBackward0>), tensor([-1.1832], grad_fn=<ViewBackward0>), tensor([-3.6766], grad_fn=<ViewBackward0>)]


# The XOR Data Set
We see that linear layers do not suffice.

In [15]:
"""
Here we create the simple XOR data set an a numpy array.
Then we make X and Y into tensor objects that torch uses,
and we package it into a Dataset object called data.
Then we create a DataLoader.
"""

Xxor = np.array([[0,0],[0,1],[1,0],[1,1]])
Yxor = np.array([0,1,1,0])
tensor_xxor = torch.Tensor(Xxor) # transform to torch tensor
tensor_yxor = torch.Tensor(Yxor)
print('These are the labels:\n',Yxor)
print('These are the features:\n',Xxor)

dataxor = TensorDataset(tensor_xxor,tensor_yxor) # create your datset
dataxor_train = DataLoader(dataxor) # create your dataloader with training data
dataxor_val = DataLoader(dataxor) # create your dataloader with validation data, here same as training

These are the labels:
 [0 1 1 0]
These are the features:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]


## Problem 9

Train your linear regressor on these data. Now see how well you do, by evaluating your solution on the training data.

Print your output. Do you get the right values?

In [16]:
# Now we train a linear classifier on these data.
# We know (and can verify) that this will fail because no linear classifier can succeed

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model3 = LinearRegressor(2, 1)# TO DO
model3.to(device)

# TO DO -- give a command to train your model
train(model3, dataxor_train, dataxor_val, device)
# TO DO -- give a command to evaluate your model
output_values = evaluate_model(model3, dataxor_val, device)

# TO DO -- print the ground truth, and then also print what your model predicts for the 4 points in the training set.
print('Ground Truth:\n',Yxor)
print('Model Output:\n',output_values)

  0%|          | 0/5000 [00:00<?, ?it/s]

Ground Truth:
 [0 1 1 0]
Model Output:
 [tensor([0.5012], grad_fn=<ViewBackward0>), tensor([0.5006], grad_fn=<ViewBackward0>), tensor([0.5005], grad_fn=<ViewBackward0>), tensor([0.4999], grad_fn=<ViewBackward0>)]


## Problem 10

Now repeat this, but using both versions of your non-linear two-layer model. Thus: train both versions of your non-linear two layer models, and evaluate them on the data.

Remember the values we got in class. We saw that there is a solution -- i.e., a setting for the parameters of the nonlinear model -- so that the network outputs the XOR outputs.

If you got the right values, try a different random seed.
If you didn't get the right values, try changing the random seed to see if you get something different.

In [19]:
#TODO: Figure out where to use random seed and test that

model4 = TwoLayerNonLinearRegressor(2, 1)
model5 = TwoLayerNonLinearRegressor2(2, 1)

model4.to(device)
model5.to(device)

train(model4, dataxor_train, dataxor_val, device)
train(model5, dataxor_train, dataxor_val, device)

output_values = evaluate_model(model4, dataxor_val, device)

print('Ground Truth:\n',Yxor)
print('Model 4 Output:\n',output_values)

output_values = evaluate_model(model5, dataxor_val, device)
print('Model 5 Output:\n',output_values)

  0%|          | 0/5000 [00:00<?, ?it/s]

  0%|          | 0/5000 [00:00<?, ?it/s]

Ground Truth:
 [0 1 1 0]
Model 4 Output:
 [tensor([-1.0790e-08], grad_fn=<ViewBackward0>), tensor([1.0000], grad_fn=<ViewBackward0>), tensor([1.], grad_fn=<ViewBackward0>), tensor([-1.0790e-08], grad_fn=<ViewBackward0>)]
Model 5 Output:
 [tensor([0.5005], grad_fn=<ViewBackward0>), tensor([0.5005], grad_fn=<ViewBackward0>), tensor([0.5005], grad_fn=<ViewBackward0>), tensor([0.5005], grad_fn=<ViewBackward0>)]


## Problem 11

If you did the above correctly, you will see that the values depend quite a bit on the random seed. In fact, you probably noticed that most random seeds **don't seem to work**.

What is happening here is that we are getting stuck in a local minimum, and our gradient-based method used in the training loop cannot escape from it.

Modify the definition of your non-linear two layer network so that the first layer of neurons (the hidden layer) has more than 2 (say, 10 or 15) neurons. Note that this means your network has more parameters.

Then run it again with different seeds on the XOR training data. Is it easier (i.e., easier to find a random seed that works)?

In [ ]:
#TODO: Everything

## Problem 12

Print the parameters of one of your non-linear models. Thus, you should print: 4 weights plus 2 bias values for the first layer, and then 2 weights plus 1 bias value for the second: 9 parameters in total.

In [ ]:
#TODO: Everything